# Docker for hosting Node REST server
# VERSION 0.0.1
# LABEL Description="Docker for hosting Node REST server" Version="0.0.1"

FROM  node:8.16.0-alpine
RUN mkdir /code
WORKDIR /code
RUN npm install -g nodemon