# Contêiner Ubuntu com iperf3 para testes de baseline (calibração) para TCC
# VERSION               0.0.3

FROM  ebiven/vue-cli
LABEL Description="vue-cli docker" Version="0.0.3"
RUN   npm install --quiet --global @vue/cli-service