# compose syntax version.
version: "3.3"

# services declaration.
services:
  # Frontend server
  frontend:
    container_name: weblock-frontend
    build: docker-images/frontend
    image: mentz/ogrc:frontend
    entrypoint: sh -c "cd /code; npm install --quiet; npm run dev"
    network_mode: host
    volumes:
      - ./frontend/:/code
    depends_on:
      - backend
    ports:
      - 8080:8080

  # Backend server
  backend:
    container_name: weblock-backend
    build: docker-images/backend
    image: mentz/ogrc:backend
    entrypoint: sh -c "cd /code; npm install --quiet; npm run dev"
    network_mode: host
    volumes:
      - ./backend/:/code
    ports:
      - 3000:3000
